Main.hs
hs-dear-imgui.cabal
src/DearImGui.hs
src/DearImGui/OpenGL.hs
src/DearImGui/SDL.hs
src/DearImGui/SDL/OpenGL.hs

This adds some cabal flags to select backends.

Add cabal flags for backend selection

---

src/DearImGui/SDL.hs

This works like SDL's `pollEvents` function, from which I copied the implementation.

Add pollEventsWithImGui function

---

src/DearImGui.hs
src/DearImGui/OpenGL.hs
src/DearImGui/SDL/OpenGL.hs

Some of the backend functions return a boolean, which was being discarded.

Return Bool when appropriate

---

cabal.project
dear-imgui.cabal
examples/vulkan/Attachments.hs
examples/vulkan/Backend.hs
examples/vulkan/Input.hs
examples/vulkan/Main.hs
examples/vulkan/Util.hs
src/DearImGui/SDL/Vulkan.hs
src/DearImGui/Vulkan.hs
src/DearImGui/Vulkan/Types.hs

I have no idea what I'm doing, so I would appreciate if you could take a look and see if this is even remotely sensible. Thanks.

Vulkan backend

---

Main.hs
dear-imgui.cabal
generator/DearImGui/Generator.hs
generator/DearImGui/Generator/Parser.hs
generator/DearImGui/Generator/Tokeniser.hs
generator/DearImGui/Generator/Types.hs
src/DearImGui.hs
src/DearImGui/Context.hs
src/DearImGui/Enums.hs
src/DearImGui/Structs.hs

First pass at trying to automatically generate some of the bindings.
I copied the "enums" section of `imgui.h` into a file, and manually removed the conditional compilation (C preprocessor directives) before passing it on to the parser (I baked in the filepath temporarily, sorry if that messes up you Nix users).
I then perform a Template Haskell splice to generate newtypes and pattern synonyms (I included the splices below).  
I am keeping track of all the docstrings in the backend, but because of Template Haskell limitations I currently don't add Haddock documentation. (This issue is slated to be fixed in `GHC 9.2`.)
While writing these I noticed two oddities:
- `ImGuiMouseCursor_None` is not `0` but `-1`, so we have to be slightly careful about that (we can't assume `None` always means …

Parse enums from headers & generate code

---

Main.hs
src/DearImGui.hs

Used listBox as a template for this since it's similar

Add combo to wrap ImGUI::Combo()

---

Main.hs
src/DearImGui.hs
src/DearImGui/Context.hs

Adds the tab bar functions: `BeginTabBar`, `EndTabBar`, `BeginTabItem`, `EndTabItem`, `TabItemButton` and `SetTabItemClosed`.

Add tab bar functions

---

cabal.project
dear-imgui.cabal

Maybe something common like "build-examples" or "development" will be a better fit.

Build executables conditionally on features

---

dear-imgui.cabal
examples/Readme.hs
src/DearImGui.hs

Add withXxx and withXxxOpen wrappers for begin/end pairs

---

src/DearImGui.hs
src/DearImGui/Raw.hs

Take 2.
- `fullscreenFlags` available for those who want an alternative
to `withFullscreen` without reinventing too much.
- `Raw.begin` got `open` and `flags` arguments.
- Added `Raw.setNextWindowFullscreen` combo block.
I decided not to break down `setNextWindowFullscreen` further due to 2 things:
- Using `setNextWindowSize` will require copying `GetIO().DisplaySize` results back and forth, or using naked `Ptr ImVec2` (which may be fine here, but that's not a right thing to do in general). I'd very much prefer to defer that to an `ImGuiIO` interface later.
- Using `setNextWindowPos` will require allocating pointers for what is basically a static `ImVec2(0, 0)`.
Maybe I'm thinking too much about those pointers...

Add withFullscreen and related machinery

---

src/DearImGui.hs
src/DearImGui/Raw.hs

- Text replaced with TextUnformatted (only in Raw)
- TextColored
- TextDisabled
- TextWrapped
- LabelText
- BulletText

Add more text widgets

---

src/DearImGui.hs
src/DearImGui/Raw.hs

- DragFloatRange2
- DragInt..4
- DragIntRange2
- DragScalar
- DragScalarN
- SliderAngle
- SliderInt..4
- SliderScalar
- SliderScalarN
- vSliderFloat
- vSliderInt
- vSliderScalar
Scalar sliders expose format and flags arguments.

Add more sliders

---

ChangeLog.md
README.md
dear-imgui.cabal

https://hackage.haskell.org/package/dear-imgui-1.0.0
Fixes #50

Prepare Hackage release.

---

src/DearImGui.hs
src/DearImGui/Raw.hs

Raw versions are specialized to match overloaded C++ functions.

Add withID

---

ChangeLog.md
Main.hs
README.md
dear-imgui.cabal
examples/Readme.hs
examples/vulkan/Main.hs
src/DearImGui/SDL.hs

Bump imgui to 1.84.2

---

ChangeLog.md
dear-imgui.cabal
src/DearImGui/GLFW.hs

Add GLFW callbacks

---

src/DearImGui.hs

- withStyleColor
- withStyleVar
- withIndent
- withItemWidth
Closes #63

Add more withXXX wrappers

---

Main.hs
src/DearImGui.hs
src/DearImGui/Raw.hs

See #67 
Plus: There is a redundant call to openGL3Shutdown, which causes Segfault when debugging in GDB

Remove seg faults

---

src/DearImGui.hs
src/DearImGui/Raw.hs

- getWindowPos
- getWindowSize
- getWindowWidth
- getWindowHeight
Closes #88

Add functions for getting window position and size

---

src/DearImGui.hs
src/DearImGui/Context.hs
src/DearImGui/Raw.hs
src/DearImGui/Structs.hs

Wrap GetCurrentContext and SetCurrentContext

---

examples/vulkan/Main.hs
src/DearImGui.hs
src/DearImGui/Context.hs
src/DearImGui/Raw.hs
src/DearImGui/Structs.hs

A bunch of `GetIO().Fonts` methods to add custom fonts.
* AddFontDefault
* AddFontFromFileTTF
* Build
* Clear

Add font utils

---

README.md
examples/Readme.hs

Update readme example

---

ChangeLog.md
dear-imgui.cabal

Bump imgui to 1.85

---

dear-imgui.cabal

Allow megaparsec 9.2

---

dear-imgui.cabal

Update unordered-containers upper limit

---

ChangeLog.md
dear-imgui.cabal

Candidate preview:
- [FontAtlas](https://hackage.haskell.org/package/dear-imgui-1.3.0/candidate/docs/DearImGui-FontAtlas.html)
- Raw
- [Font](https://hackage.haskell.org/package/dear-imgui-1.3.0/candidate/docs/DearImGui-Raw-Font.html)
- [Font.Config](https://hackage.haskell.org/package/dear-imgui-1.3.0/candidate/docs/DearImGui-Raw-Font-Config.html)
- [Font.GlyphRanges](https://hackage.haskell.org/package/dear-imgui-1.3.0/candidate/docs/DearImGui-Raw-Font-GlyphRanges.html)

Prepare 1.3.0

---

ChangeLog.md
dear-imgui.cabal

Update upstream to 1.86

---

examples/glfw/Main.hs
src/DearImGui.hs
src/DearImGui/Raw.hs

- BeginPopupContextItem
- BeginPopupContextWindow
- BeginPopupContextVoid
For #132

Add remaining popup wrappers

---

src/DearImGui.hs
src/DearImGui/Context.hs
src/DearImGui/Raw.hs
src/DearImGui/Structs.hs

Implements https://github.com/haskell-game/dear-imgui.hs/issues/130
Could be used as-is - sorting & misc-functions are still missing.
More to come.

implementation of ImGui Tables

---

examples/glfw/Main.hs
src/DearImGui.hs
src/DearImGui/Raw.hs
src/DearImGui/Structs.hs

Tweak tables and add an example

---

src/DearImGui.hs

Make value and read-only range types distinct

---

Main.hs
dear-imgui.cabal
examples/glfw/Main.hs
src/DearImGui.hs
src/DearImGui/Internal/Text.hs

Shave a few allocations due to conversion.
Should alleviate #47.

Replace String arguments with Text

---

ChangeLog.md
dear-imgui.cabal

Prepare 2.1.0

---

dear-imgui.cabal

The example needs the opengl2 flag.

Fix the glfw example build condition

---

src/DearImGui.hs
src/DearImGui/Raw.hs

This change enables starting a new TreeNode open.

Add setNextItemOpen

---

dear-imgui.cabal

Fix cabal flag for image example

---

dear-imgui.cabal
generator/DearImGui/Generator/Parser.hs
src/DearImGui/SDL.hs
src/DearImGui/SDL/OpenGL.hs
src/DearImGui/SDL/Vulkan.hs

upgraded imgui to v1.89.7; Downstream-breakage **possible**

---

Main.hs
src/DearImGui.hs
src/DearImGui/Raw.hs

Fix TabItem flags type

---

src/DearImGui.hs

found these typos, looking forward to using the library :)

fix intem->item

---

src/DearImGui/SDL.hs

Adds `dispatchRawEvent` function to the SDL backend.

Add support for dispatching raw SDL events to Dear ImGui
