haskell-game/dear-imgui.hs

- src/DearImGui.hs
fixes compilation error on darwin
> add string formatter to `text`

- dear-imgui.cabal
The if conditionals were incorrectly nested, which caused a problem with OpenGL on Windows.
> Fix conditional in cabal file

- .gitignore
This file gets generated by routine testing but we'll never want to commit it.
> Ignore imgui.ini

- cabal.project
- dear-imgui.cabal
- default.nix
- examples/glfw/Main.hs
- src/DearImGui/GLFW.hs
- src/DearImGui/GLFW/OpenGL.hs
- src/DearImGui/GLFW/Vulkan.hs
I've only tested this on Windows with OpenGL (example included).
I'm not sure why but I needed to use `pkgconfig-depends: glfw3` to get linking to work using Chocolatey although `extra-libraries` is sufficient to SDL2 to link. For reference, I used to following to install the dependencies:
```powershell
mingw64-pkg.bat install pkg-config
mingw64-pkg.bat install SDL2
mingw64-pkg.bat install glfw
```
> Add support for GLFW

- src/DearImGui.hs
- src/DearImGui/Context.hs
Just doing a little cleanup:
- some functions were not exported,
- some functions were missing the initial `|` for their documentation,
- add types to the ImGui Context instead of coercing to `int`. This is more robust, in case upstream changes any of the larger enums to be `64` bits instead of `32` for instance.
> Define types for use in ImGui Context

- dear-imgui.cabal
This works for me on Windows. I haven't tested on macOS but we might as well leave it like this rather than `unbuildable` until we learn otherwise.
> Allow building of OpenGL3 component on Windows

- dear-imgui.cabal
- generator/DearImGui/Generator.hs
- generator/DearImGui/Generator/Parser.hs
- generator/DearImGui/Generator/Types.hs
- src/DearImGui/Context.hs
This handles the remaining enum types in the headers that aren't in the enums section.    
It also automatically handles adding all the enumerations to the `inline-c` context types table, and a small improvement to the display of parse error messages.
> Handle remaining enums

- generator/DearImGui/Generator.hs
- generator/DearImGui/Generator/Types.hs
I have no idea why the version with `newName` caused the issue experienced by falling-edge, but this fixes it.
> Generator: use mkName instead of newName

- dear-imgui.cabal
This change follows up on https://github.com/haskell-game/dear-imgui.hs/pull/41
where it seems like cabal still need the examples dependency even when they are
not buildable, e.g.: `next goal: vulkan-utils (dependency of dear-imgui)` with
cabal-install version 3.2.0.0.
> Disable build-depends when not building executables

- generator/DearImGui/Generator.hs
- generator/DearImGui/Generator/Parser.hs
This contains two small changes for GHC 9.2:
1. Update the Template Haskell part of the generator which adds the docstrings, to adapt for some changes in the `putDoc` API that is part of GHC 9.2.
2. Address some warnings involving duplicate record fields.
> Update generator for GHC 9.2

- src/DearImGui.hs
- src/DearImGui/Raw.hs
Required for skipping input events in app areas occluded and, presumably, handled by DearImGui.
> Add wantCaptureMouse, wantCaptureKeyboard

- src/DearImGui/Vulkan.hs
This allows users to manually call `vulkanInit` and `vulkanShutdown` in more general contexts, e.g. when they have their own custom monads which aren't instances of `MonadUnliftIO`.
> Relax MonadUnliftIO constraint on vulkanInit

- Main.hs
- src/DearImGui.hs
- src/DearImGui/Raw.hs
Old behaviour with all default arguments is a special case to run
some action scoped to a different child window.
This now handled by `beginChildContext`/`withChildContext`.
> Add remaining BeginChild arguments as required

- default.nix
Switches the default Nix build to use GHC 8.10.7 and NixOS 21.05
> Nix upgrades

- dear-imgui.cabal
Implements #104 (Thanks to @dpwiz for the Common Stanzas tip)
Added debug mode (eg. `cabal run -f debug image`).
1. For normal compiling increased the optimiaztion level to O2
2. Tested only for Linux
3. MinGW (Windows) does not support address sanitizer. GCC 4.8 and llvm 3.something does - is it ok, to assume newer version?.
4. Added cxx-flags to the c-flags.
> Added compiler flags stanzas.

- src/DearImGui.hs
- src/DearImGui/Raw.hs
Small patch to open popups when the last item with ID gets clicked interactively (without the programmer having to care about the state).
Just wraps the corresponding ImGui-Call.
> added openPopupOnItemClick

- dear-imgui.cabal
Exposed the "#define ImDrawIdx unsigned int" from the imconfig.h for external configuration.
It is needed when you want to draw "more" vertices in an object (as i need with the implot-extension) without resorting to (inefficient) hacks with offsets etc. for the expense of a bit of memory-bloat in the indexes.
Similar tradeoffs to the WCHAR32-flag already present of using 32 instead of 16 bits.
> added flag_ImDrawIdx

- dear-imgui.cabal
Fixes errors along the lines of:
dear-imgui  > [ 2 of 17] Compiling DearImGui.GLFW
dear-imgui  > error: unknown type name 'constexpr'
So the "-std=c++11" option is not being passed to the C++ compiler on MacOS 12.5.1 (GHC 8.10.7, Stack 2.7.5, Cabal 3.6.2.0).
The issue seems potentially related to https://github.com/haskell/cabal/issues/6421
Doesn't seem like this should be necessary with newer versions of Cabal, but nevertheless, this fix is needed and 'works for me'.
May be worth revisiting in the future.
Closes #155
> Fix compilation on MacOS / GHC 8.10.7

- src/DearImGui/Internal/Text.hs
This fixes a bug that causes many different symptoms, from flickering text to segmentation faults.
It makes sense, given the nature of the bug.
Thanks,
Rodrigo
> Fix off-by-one bug in string null termination

- dear-imgui.cabal
vulkan, vulkan-utils and VMA can be too old/new for each other. This cuts a fresh, known-to-work set of lower bounds.
> Fix vulkan versions to a fresh set

- dear-imgui.cabal
- src/DearImGui/Raw.hs
- src/DearImGui/Raw/Context.hs
- src/DearImGui/Raw/DrawList.hs
- src/DearImGui/Raw/Font.hs
- src/DearImGui/Raw/Font/Config.hs
- src/DearImGui/Raw/Font/GlyphRanges.hs
- src/DearImGui/Raw/IO.hs
- src/DearImGui/Raw/ListClipper.hs
I required this module to implement an extension to dear-imgui (gradient editor based on a c++ gist)
I moved `DearImGui.Context` to `.Raw` and exposed it from the cabal file.
> Expose DearImGui.Raw.Context

- src/DearImGui.hs
- src/DearImGui/Raw.hs
Get cursor position in window-local coordinates.
Useful to overlap draw using 'setCursorPos'.
> Add getCursorPos

- src/DearImGui/Vulkan.hs
`init_info` got dynamic render flag, which is a breaking change with its default value. Setting it to `false` will fix validation errors coming from misconfiguration.
> Fix vulkan init wrapper

- README.md
- examples/Readme.hs
Update the README example to use OpenGL 3 instead of OpenGL 2, following the suggested package flags.
Not only does this modernise the example to use a more recent OpenGL version, it also prevents possible confusion for a beginner where the example doesn't work. This is because the code uses OpenGL 2 whereas the README suggests using the `opengl3` flag (see #95).
Some other minor improvements:
- Remove the use of unnecessary extensions like `BlockArguments` that some people might not be familiar with
- Specify some imports more precisely
- Simplify some control flow
> Update README example

- src/DearImGui.hs
- src/DearImGui/Raw.hs
> Add support for disabled blocks

- dear-imgui.cabal
When testing a Windows application using `dear-imgui` and `file-embed` with GHC 9.4.8, I bumped into [this build issue](https://gitlab.haskell.org/ghc/ghc/-/issues/22738):
```
<no location info>: error:
addDLL: stdc++ or dependencies not loaded. (Win32 error 126)
```
The same application worked fine on Mac and I'm not yet familiar enough with Windows development to understand why the Windows side wasn't happy. Regardless, following the recommendation in the linked issue and the GHC 9.4 migration guide to [link against the virtual `system-cxx-std-lib` instead of `stdc++`](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.4#link-against-system-cxx-std-lib-instead-of-stdc) for 9.4+ gets things working on Windows and the Mac build continues to work.
---
Unrelated to this PR's changes, …
> Link against system-cxx-std-lib for GHC 9.4+

- dear-imgui.cabal
This change relax the vulkan executable constraint to match the one of the library.
> Adjust vulkan text constraint for ghc-9.8

- dear-imgui.cabal
This change prevents building against sdl2 version 1 which does not have the necessary exposed modules.
> Set proper sdl2 min bound

- examples/vulkan/Main.hs
- src/DearImGui/Vulkan.hs
- src/DearImGui/Vulkan/Types.hs
Exposes two new properties for the Vulkan implementation:
- `useDynamicRendering` - for use in more modern dynamic rendering pipelines
- `colorAttachmentFormat` - [required to enable dynamic rendering
](https://github.com/ocornut/imgui/blob/6f7b5d0ee2fe9948ab871a530888a6dc5c960700/backends/imgui_impl_vulkan.cpp#L49)
Relevant Vulkan docs:
- https://github.com/KhronosGroup/Vulkan-Docs/blob/main/proposals/VK_KHR_dynamic_rendering.adoc
There may be more considerations here, but this seems to work as-is so far as I can tell.
> Expose Vulkan dynamic rendering

- src/DearImGui.hs
- src/DearImGui/Raw.hs
If, for example, you want to 'select' a tree node, you would need to pass in the ImGuiTreeNodeFlags_Selected flag. This function allows rendering tree nodes with flags.
> Add Tree Node function that accepts flags

- examples/sdl/Image.hs
- examples/vulkan/Main.hs
- generator/DearImGui/Generator/Parser.hs
- src/DearImGui/Raw.hs
This is a small PR which does the minimum work required to update imgui to 1.91.3. No new features are supported. The one breaking change is that it changes the signature of `imageButton`.
This is needed for SDL3 support, which will come in a separate PR (and depends on the yet unreleased sdl3-hs package). 1.91.3 is the first version that comes close enough to the current version of SDL3 to support it.
I believe this closes #214
> Update imgui dependency to 1.91.3 (Released 2024-10-04)
